[build-system]
requires = ["setuptools"]
build.backend = "setuptools.build_meta"

[project]
name = "dockerproject"
requires-python = ">=3.12"
version = "0.0.1"
dependencies = [
    "fastapi" ,
    "motor" ,
]
[tools.setuptools.packages.find]
where = ["src"]